#### NOVA IMS / BSc in Data Science / Text Mining 2025/2026
### <b>Group Project: "Straining the great southern Melting Pot"</b>
#### Notebook `Text Mining Project`

#### Group:
- `Cyrine Moalla 20230003`
- `Khadija Belhamra 20230007`
- `Victoriya Mokhovikova 20230796`
- `Vlad Botnev 20230795`

#### <font color='#BFD72'>Table of Contents </font> <a class="anchor" id='toc'></a> 
- [1. Data Understanding](#P1)
- [2. General Data Preparation](#P2) 
- [3. Multilabel Classification (Information Requirement 3311)](#P3)
    - [3.1 Specific Data Preparation](#P31)
    - [3.2 Model Implementation](#P32)
    - [3.3 Model Evaluation](#P3n)
- [4. Sentiment Analysis (Information Requirement 3312)](#P4)
    - [4.1 Specific Data Preparation](#P41)
    - [4.2 Model Implementation](#P42)
    - [4.3 Model Evaluation](#P43)
- [...]
- [N. Additional Tasks (Information Requirements 332n)](#Pn)
    - [N.1 Specific Data Preparation](#Pn1)
    - [N.2 Model Implementation](#Pn2)
    - [N.3 Model Evaluation](#Pn3)

<i>## Note that the notebook structure differs from the report: instead of following the CRISP-DM phases and then specifying the different problems inside the phases, the notebook is structured by problem, with the CRISP-DM phases being defined for each specific problem.

In [1]:
## All imports must be concentrated on a cell that immediately follow the table of contents
import time
import pandas as pd
import re

<font color='#BFD72F' size=5>1. Data Understanding</font> <a class="anchor" id="P1"></a>
  
[Back to TOC](#toc)

<i>## Use markdown cells to describe the purpose of the code cells that follow them.</i>

Let's start buy reading the dataset

In [5]:
## Functions must be defined on separate cells
def text_mining_project_simulator():
    project_progress = 0
    while project_progress < 100:
        ## Comments on code cells can be used to highlight specific sections of yout code
        project_progress += 1
        print("working, albeit reluctantly, on a project that's {}% done \n\n".format(project_progress))
        time.sleep(5)

In [6]:
## Calls to functions (whether defined by the group, or imported from packages) must be separate from their definition

text_mining_project_simulator()

working, albeit reluctantly, on a project that's 1% done


working, albeit reluctantly, on a project that's 2% done

KeyboardInterrupt:

<font color='#BFD72F' size=5>3. Preprocessing for task 2</font> <a class="anchor" id="P1"></a>


This step focuses on preparing the data for the sentiment analysis task.


![preprocessing pipeline for TM](images/RuleBasedApproache.png)

For this task, a rule-based algorithm will be used. As our dataset consists of online reviews, the speech is expected to be informal, thus the VADER algorithm is the most appropriate for this task. Therefore, we will preprocess the data to meet VADER's requirements.

<i> Notes:
- Emojis should be kept
- Letter case should be preserved
- Stopwords should be kept
- Punctuation should be preserved
- No stemming or lemmatization will be applied
- Tokenization will follow a one sentence = one token approach to preserve context</i>

In [2]:
from nltk.tokenize import PunktSentenceTokenizer
from nltk.sentiment import SentimentIntensityAnalyzer
from scipy.stats import pearsonr

In [3]:
## Source code of the VADER module
# import inspect
# from nltk.sentiment import vader
# print(inspect.getsource(vader))

In [4]:
# Import data
atlanta_rest = pd.read_csv("data_atlanta/atlanta_restaurant_slice_2023.csv", header=0)

atlanta_rest.head(1)

,title,categoryName,website,url,reviewsCount,stars,text
0,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,"One word amazing!! The red fish, halibut, fr..."

In [5]:
# Drop unneeded columns
atlanta_rest = atlanta_rest.drop(columns=["categoryName",
                                            "website",
                                            "url",
                                            "reviewsCount"])
atlanta_rest.head()

          title  stars                                               text
0  The Optimist    5.0  One word amazing!! The red fish,  halibut,  fr...
1  The Optimist    5.0  First time here and the food is great and the ...
2  The Optimist    5.0  I recently had the pleasure of dining at Optim...
3  The Optimist    5.0  Beautiful atmosphere and delicious food. All o...
4  The Optimist    5.0  We had a wonderful dinner at the Optimist. Our...

In [6]:
# Check NaNs
atlanta_rest.isna().sum()

title    0
stars    0
text     0
dtype: int64

In [7]:
# Since there is no cleaning nor normalization needed
# We can move on to tokenization

tokenizer = PunktSentenceTokenizer()
atlanta_rest['prepro_text'] = atlanta_rest['text'].apply(tokenizer.tokenize)

In [ ]:
v_analyzer = SentimentIntensityAnalyzer()

atlanta_rest["sentiments"] = atlanta_rest["prepro_text"].apply(
    lambda sentences: [v_analyzer.polarity_scores(s)["compound"] for s in sentences]
)

In [16]:
from statistics import mean
atlanta_rest["avg_comp"] = atlanta_rest["sentiments"].apply(
    lambda compounds: mean(compounds))

In [17]:
pearson_r, p_value = pearsonr(atlanta_rest["avg_comp"], atlanta_rest["stars"])
pearson_r

0.6675443726630419